#!/bin/sh

_gimp2dir1=/usr/lib/gimp/2.0/plug-ins
_gimp2dir2=/opt/gnome/lib/gimp/2.0/plug-ins

for LIBS in libcncpmsimg libcncpmslld libcncpcmcm libcncpmsui libcncpnet
do
	if [ -h /usr/lib/${LIBS}.so ]; then
		rm -f /usr/lib/${LIBS}.so
	fi	
done

# remove symbolic link for gimp-plug-in
rm -f ${_gimp2dir1}/scangearmp
rm -f ${_gimp2dir2}/scangearmp

# remove sgmp_setting files
rm -f /var/tmp/canon_sgmp_setting*.*
rm -f /tmp/canon_sgmp_setting*.*
