/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_preference_window (void);
GtkWidget* create_select_model_dialog (void);
GtkWidget* create_save_main_dialog (void);
GtkWidget* create_save_overwrite_dialog (void);
GtkWidget* create_save_error_dialog (void);
GtkWidget* create_dialog_bright_contrast (void);
GtkWidget* create_dialog_histogram (void);
GtkWidget* create_dialog_tonecurve (void);
GtkWidget* create_dialog_final_review (void);
GtkWidget* create_dialog_monochrome (void);
GtkWidget* create_dialog_calibration (void);
GtkWidget* create_error_dialog (void);
GtkWidget* create_dialog_about (void);
GtkWidget* create_dialog_clear_preview (void);
GtkWidget* create_dialog_progress_bar (void);
GtkWidget* create_dialog_child_with_checkBox (void);
GtkWidget* create_dialog_child_with_ok (void);
GtkWidget* create_dialog_child_with_okcancel (void);
GtkWidget* create_dialog_quiet_settings (void);
GtkWidget* create_dialog_get_settings (void);
GtkWidget* create_dialog_autopower_settings (void);
